name = "rsc-server-do"
main = "entry-server.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Durable Objects
[durable_objects]
bindings = [
    { name = "GAME_WORLD", class_name = "GameWorld" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameWorld"]

# KV Namespaces
[[kv_namespaces]]
binding = "KV"
id = "f2881801ac59415a86236d0841f27103"

# Environment Variables
[vars]
MEMBERS = "true"

[[rules]]
type = "Data"
globs = ["**/*.jag", "**/*.mem"]
fallthrough = true
